Реализация основной функциональности приложения
SinitsaBogdan/blog-customizer pull request #3
Opened 2024-09-18 19:39 UTC by SinitsaBogdan

2024-09-18 20:36 UTC, SergeyK2004 requested changes
Добрый день! 

У вас получилась отличная работа:
* Почти полностью реализован функционал.
* Типизированы все пропсы


Но есть пара моментов, который надо поправить:

- За состояние страницы отвечает компонент `App`, а за состояние формы компонент `ArticleParamsForm`. Нужно продумать логику передачи данных от `App` в форму и обратно.
- Компонент страницы не должен знать про состояние формы. Состояние формы надо перенести в компонент `ArticleParamsForm`. Туда же нужно перенести все обработчики.
- Для условного добавления стилей лучше воспользоваться библиотекой `clsx`.
- Сайдбар должен закрываться по клику за пределами сайдбара.

Правки можно лучше остаются на ваше усмотрение:

- Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.
- Обработчик клика по оверлею для закрытия сайдбара лучше попробовать реализовать через кастомный хук.
- Использовать один обработчик для событий `onChange` на элементах формы

Успешного рефакторинга!

2024-09-18 20:36 UTC, SergeyK2004 commented on src/components/arrow-button/ui/ArrowButton.tsx
> +			className={`${styles.container} ${isOpen && styles.container_open}`}
**Надо исправить:**

Для указания условия в стилях необходимо использовать библиотеку clsx.

2024-09-18 20:36 UTC, SergeyK2004 commented on src/components/article-params-form/ui/ArticleParamsForm.tsx
> +	setState,
Надо исправить:
Нужно передать в компонент только функцию изменения состояния

2024-09-18 20:36 UTC, SergeyK2004 commented on src/components/article-params-form/ui/ArticleParamsForm.tsx
> +				className={`${styles.container} ${isOpen && styles.container_open}`}>
**Надо исправить:**

Для указания условия в стилях необходимо использовать библиотеку clsx.

2024-09-18 20:36 UTC, SergeyK2004 commented on src/components/article-params-form/ui/ArticleParamsForm.tsx
> +						<Button title='Применить' type='button' onClick={save} />
**Можно лучше:**

Обработчик сохранения данных должен вызываться при отправке формы и достаточно обработать только событие отправки формы. Не нужно вешать его на кнопку, нужно вызывать его при отправке формы

2024-09-18 20:36 UTC, SergeyK2004 commented on src/index.tsx
> +	const dom = useRef<HTMLDivElement | null>(null);
**Надо исправить:**
Состояние настроек нужно хранить в стэйте формы, создавать и отдельно хранить ссылку на объект через `ref` не имеет смысла

2024-09-18 20:36 UTC, SergeyK2004 commented on src/index.tsx
>  const App = () => {
**Можно лучше:**

Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.

2024-09-18 20:36 UTC, SergeyK2004 commented on src/index.tsx
> +	function handlerOnClickToSave(): void {
**Надо исправить:**

Каждый компонент сам должен отвечать за хранение и обработку своего состояния. Использовать подъем состояния в родительский компонент не имеет смысла для нашего приложения. Состояние формы нужно описать в самом компонент `ArticleParamsForm`, а не передавать его из `App`, т.к. это состояние описывает именно `ArticleParamsForm`. В состоянии `App` должны хранится только данные о текущем отображении статьи.

2024-09-18 20:36 UTC, SergeyK2004 commented on src/index.tsx
> +				save={handlerOnClickToSave}
Надо исправить:
Состояние формы и обработчики должны находиться в самом компоненте формы. Вам необходимо из компонента статьи передавать только функцию изменения состояния, для возможности изменять отображение статьи при сабмите новых настроек.

2024-09-19 10:26 UTC, SinitsaBogdan commented on src/components/arrow-button/ui/ArrowButton.tsx
> +			className={`${styles.container} ${isOpen && styles.container_open}`}
DONE

2024-09-19 10:41 UTC, SinitsaBogdan commented on src/components/article-params-form/ui/ArticleParamsForm.tsx
> +				className={`${styles.container} ${isOpen && styles.container_open}`}>
DONE

2024-09-19 10:49 UTC, SinitsaBogdan commented on src/index.tsx
>  const App = () => {
DONE

2024-09-19 11:11 UTC, SinitsaBogdan commented on src/index.tsx
> +	const dom = useRef<HTMLDivElement | null>(null);
DONE

2024-09-19 12:32 UTC, SinitsaBogdan commented on src/components/article-params-form/ui/ArticleParamsForm.tsx
> +	setState,
DONE

2024-09-19 12:43 UTC, SinitsaBogdan commented on src/index.tsx
> +	const dom = useRef<HTMLDivElement | null>(null);
тут я не совсем понимаю как правильно делать
в первый раз у меня было через useRef для доступа к элементу страницы

теперь же через useState, если что же не верно то я пока не понимаю как из дочернего компонента получить доступ к стилям родительского.

```
const [articleState, setArticleState] = useState(defaultArticleState);

	function updateStyle(params: ArticleStateType) {
		setArticleState(params);
	}

	return (
		<div
			className={clsx(styles.main)}
			style={
				{
					'--font-family': articleState.fontFamilyOption.value,
					'--font-size': articleState.fontSizeOption.value,
					'--font-color': articleState.fontColorOption.value,
					'--container-width': articleState.contentWidthOption.value,
					'--bg-color': articleState.backgroundColorOption.value,
				} as CSSProperties
			}>
			<ArticleParamsForm update={updateStyle} />
			<Article />
		</div>
	);
```

2024-09-19 12:46 UTC, SinitsaBogdan commented on src/index.tsx
> +	function handlerOnClickToSave(): void {
DONE

2024-09-19 12:48 UTC, SinitsaBogdan commented on src/index.tsx
> +				save={handlerOnClickToSave}
DONE

2024-09-19 18:09 UTC, SergeyK2004 requested changes
Отличная работа.
Практически все недочеты устранены.
Осталось только реализовать закрытие формы по клику в оверлей.

2024-09-20 17:49 UTC, SergeyK2004 requested changes
Здорово, что вы решили создать кастомный хук. Это хорошая практика. необходимо только немного его доработать. Посмотрите комментарии в коде.

2024-09-20 17:49 UTC, SergeyK2004 commented on src/components/article-params-form/hooks/useToggleFormActiv.ts
> +						item === document.querySelector(`[data-element="${element}"`)
Богдан, данный подход некорректен для Реакта. Мы не используем теперь `document.querySelector`, так как разметка создается динамически. Для получения ссылки на создаваемый элемент следует использовать ref
Кроме того, вы реализуете закрытие формы, а опираетесь при этом на элементы компонента статьи, что так-же недопустимо. Статья не должна участвовать в логике работы формы. Компоненты являются независимыми друг от друга и могут свободно быть переиспользованы в приложении. 
Обратите внимание на хук useOutsideClickClose, который есть в компоненте Select. 
Для понимания работы ref вы всегда можете обратиться к вашему наставнику.

2024-09-20 17:49 UTC, SergeyK2004 commented on src/components/article/ui/Article.tsx
> +		<article className={clsx(styles.article)} data-element='article'>
Добавлять в элемент атрибуты для работы других компонентов недопустимо.  Это нарушает основные принципы ООП. Высокой связанности между компонентами не должно быть.

2024-09-20 20:16 UTC, SinitsaBogdan commented on src/components/article-params-form/hooks/useToggleFormActiv.ts
> +						item === document.querySelector(`[data-element="${element}"`)
DONE

2024-09-21 20:43 UTC, SergeyK2004 approved these changes
Отличная работа. Поздравляю со сдачей проекта.
Желаю успехов в дальнейшем обучении.

2024-09-22 07:42 UTC, SinitsaBogdan commented
Завершение реализации основного функционала приложения

2024-09-22 07:42 UTC, merged